name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build

      - name: Coverage
        run: go test -short -coverprofile cover.out -covermode=atomic ./...

      - name: Upload coverage report to Codacy
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get github.com/schrej/godacov
          godacov -t $CODACY_TOKEN -r ./cover.out -c $GITHUB_SHA
        env:
          CODACY_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}